apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: argocd
type: Opaque
data:
  username: c2h5YW1heWFkYXYxNTRAZ21haWwuY29t
  password: c2h5YW1AMTU0


# encode shyamaydav154@gmail.com to base64